### ISSUE TITLE
Support for livestock cars

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#218]
Idea:
* Lasso a entity
* Drag it next to the car
* Right click on the car with the lasso
* Entity rides car
* Right click on the car with a lasso
* One of the entities dismounts and is lassoed (ideally)

**Comment by MauveCloud** [comment]
By "lasso" I presume you mean a "lead" that is sometimes called a "leash" to reduce confusion with the metal that's spelled the same, rather than requiring an XU2 golden lasso.  However, I hope it will also be possible to use mob transportation items from other mods, such as said golden lasso or TE morbs, to get the entities onto the livestock cars.

**Comment by FoxyRavenger** [comment]
The unload feature could be a button for left or right dismounting of stock, no need for a lead
