### ISSUE TITLE
New train suggestion

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#392]
Is there any chance to add the Rapid/Bullet train such as "Japanese Shinkansen" ?
I want to enjoy this mod at very high speed.
Also, I think it is good to add speed config option.

**Comment by EScapeTheShadows** [comment]
Are you asking about adding the locomotive specifically? Because I know that someone is adding in the ICE locomotive. Most locomotives for this mod are made by modellers and added in as resource packs. If you are asking about the systems for it, banked curves are on the todo list, but really it’s what your processor can handle, as the faster you go the more it’s going to struggle. I believe that the speed record in the mod is somewhere around Mach 2, but don’t quote me on that.
