### ISSUE TITLE
Allow Tracks to be placed on Scaffolding

### ISSUE THREAD

**Issue by Railroadactive** [cam72cam/ImmersiveRailroading#502]
I find it interesting that tracks can't be laid over scaffolding even though scaffolding is a block. It would certainly make things easier when routing pipes underneath the track

**Comment by dragonshardz** [comment]
Scaffolding is a transparent block, which the default configuration does not allow as a supporting block for rails. There is a configuration option which will allow rails to be placed on scaffolding.

That said, adjusting the configuration structure to have a specific list of transparent blocks that are allowed instead of a simple binary switch would be a good change.
________________________________
