### ISSUE TITLE
IR's rails and BuildHelper Mod crash

### ISSUE THREAD

**Issue by Eulerdice** [cam72cam/ImmersiveRailroading#647]
By using the [BuildHelper Mod](http://www.9minecraft.net/buildhelper-mod/)'s universal fill wand (which fills a selected area with a selected block type) you can corrupt your world. If you try to fill an area of any size with IR's rails, it will result in a game crash, which happens every time you try to load the chunk in which this was done. Upon removing IR the save becomes usable again but if you try to add IR back, the crash will be back.

Crash report: https://pastebin.com/wF5S0xtY

I have been trying to fix the save file so that I may use IR once again but without any success. Would really appreciate any help as I've been working on this world for a long time and it's not the same without IR. Thank you.

**Comment by FriedrichLP** [comment]
This is an obvious crash to anyone who is familiar with IR's inner workings.
Each IR track stores extra information about the track-bed, length, track type and so on. This data is set when you place down the track using the track blueprint and is (almost) impossible to set using other means. This bug is also not fixable and I would not even see it as a bug.
You can fix your world though by either setting "B:removeErroringEntities" in the forge.cfg inside your config folder to true (which will delete the tracks as soon as they would cause a crash) or by editing the world in a program like McEdit and deleting the blocks where the track should be

**Comment by Larky2k** [comment]
you mite be able to save the world you will need to use a MCEdit program to delete the chunk the source block of the rail is in and then regen that chunk.

**Comment by Larky2k** [comment]
also lay track by hand and not using any mod to quickly do it that will save you from crashing again

**Comment by Eulerdice** [comment]
Thanks, I did not realise there was a mcedit that worked with 1.12.2 but then I tried mcedit unified and it worked. Also using "B:removeErroringEntities" did not stop the crash.
